# Generated by Django 5.1 on 2024-08-24 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveIntegerField(unique=True)),
                ('bio', models.TextField(blank=True, help_text='Tell the galaxy about yourself.', max_length=500)),
                ('profileimg', models.ImageField(default='default_profile.jpg', help_text='Upload your intergalactic avatar.', upload_to='profile_images/')),
                ('planet', models.CharField(blank=True, help_text='Your home planet.', max_length=100)),
                ('star_system', models.CharField(blank=True, help_text='The star system you belong to.', max_length=100)),
                ('species', models.CharField(blank=True, help_text='Your species.', max_length=100)),
                ('interests', models.CharField(blank=True, help_text='What interests you in the cosmos?', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
