# Generated by Django 5.1 on 2024-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warperprofile', '0002_profile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='default.jpg', help_text='Upload your intergalactic avatar.', upload_to='profile_images/'),
        ),
    ]
