# Generated by Django 5.1 on 2024-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warperprofile', '0004_post_like_repost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='original_post',
        ),
        migrations.RemoveField(
            model_name='repost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
